### ISSUE TITLE
undefined gutter variable when trying to include flex-grid

### ISSUE THREAD

**Issue by shicholas** [zurb/foundation-rails#137]
Hello,

Thanks for upgrading this gem to Foundation 6. I'm excited to implement this in my project. When trying to replace the ``@include foundation-grid`` with ``@include foundation-flex-grid`` in my ``foundation_and_overrides.scss`` file I get this error: 

```
Showing /home/nick/stealth/web/app/views/layouts/application.haml where line #7 raised:

Undefined variable: "$gutter"
```

Is there an "official" way to include the flex grid instead of the regular one?!

**Comment by arthurzurb** [comment]
Hey @shicholas,

I am going to be closing this, take a look at the issue here: https://github.com/zurb/foundation-sites/issues/7857

This is not a Rails Gem issue, but feel free to report them as you come across any issues installing the gem! Thanks! :smile:
