### ISSUE TITLE
issues getting the close-button to work

### ISSUE THREAD

**Issue by shicholas** [zurb/foundation-rails#138]
sorry for the spam, but I can't seem to quite get the close-button working.

application.js

```js
//= require foundation
//= require turbolinks

$document.on('page:load ready', function() {
  $(document).foundation();
})
```

haml file for rending a flash message as a callout

```haml
- if notice
  .success.callout{ data: { closable: '' } }
    = notice
    %button.close-button{ aria: { label: 'Dismiss alert' }, data: { close:  '' }, type: 'button' }
      %span{'aria-hidden' => 'true'} ×
- if alert
  .alert.callout{ data: { closable: '' } }
    = alert
    %button.close-button{ aria: { label: 'Dismiss alert' }, data: { close:  '' }, type: 'button' }
      %span{'aria-hidden' => 'true'} ×
```

I got the navbar working so I don't think it's a JS issue, but perhaps I'm missing something? Any advice would be appreciated.

Thank you,

**Comment by Deckluhm** [comment]
It doesn't look like an issue related to the gem, you should post your issue in this repo: https://github.com/zurb/foundation-sites

I also tried to make closable components work but without success, there is probably a bug (or something missing in the documentation).

**Comment by gakimball** [comment]
I believe this is because the Motion UI CSS isn't loaded. We don't currently have a gem for Motion UI (just npm and Bower packages), but we could publish one.

We also need a better fallback if Motion UI isn't loaded.

**Comment by arthurzurb** [comment]
Closing this since it is in the Foundation Sites repo

**Comment by weiserma** [comment]
I just added the motion-ui classes to my application.sccs file and it worked.

**Comment by zurbchris** [comment]
Awesome!

**Comment by arthurzurb** [comment]
Great to hear, we decided to keep Motion UI out of the Gem since it is an add-on to Foundation for Sites.

**Comment by shicholas** [comment]
great, thank you!

**Comment by weiserma** [comment]
I think you should include the motion ui css in the gem, so that changes 
are kept in sync.

**Comment by gakimball** [comment]
@weiserma Agreed, we could publish a separate gem but it might be easier to bundle them together.
