### ISSUE TITLE
Adding vertical/horizontal classes to data-responsive-menu

### ISSUE THREAD

**Issue by shicholas** [zurb/foundation-rails#144]
I really like how I can switch between a drilldown and a dropdown with http://foundation.zurb.com/sites/docs/responsive-navigation.html, but is there a way to make the ``li`` elements toggle between ``horizontal`` and ``vertical`` with this? Or should I stick with visibility classes?

thank you,

**Comment by Deckluhm** [comment]
This repository is about the Foundation gem, not the actual framework.

You should post your issue here: https://github.com/zurb/foundation-sites

**Comment by shicholas** [comment]
thank you will do.
