### ISSUE TITLE
couldn't find file 'foundation' with type 'application/javascript' in ruby on rails

### ISSUE THREAD

**Issue by Rehankhan100** [zurb/foundation-rails#145]
i follow your instruction from Installation section to Motion UI section i add gem 'foundation_rails' line in my gemfile and then run bundle install and after install i run rails g foundation:install and 
<h1>Method 1:</h1>
its show to override 
i select Y (yes) to override then its create 2 files in app folder

1 app/assets/stylesheets/_settings.scss 
2 app\assets\stylesheets\foundation_and_overrides.scss 

and then i look in to javascript folder app/assets/javascript their is only one file application.js and in application.js two line added automatically 

1 //= require foundation
2 $(function(){ $(document).foundation(); });

and in application.html.erb file its change some lines which use to call stylesheet and javascript files.

<h1>Method 2:</h1>
its show again to override
then i select n (no) to override then its again create same files as create in Method 1

but the problem remain same.

i try both Methods but every time localhost:3000 page shows some error's
![foundation_rails_error](https://cloud.githubusercontent.com/assets/8132386/12468250/a1218c06-c003-11e5-8372-1d677a9371bf.png)

what should i do kindly solve my problem asap.

**Comment by Deckluhm** [comment]
Did you restart the server after installing the gem?

And I guess this is just a typo but the gem name is `foundation-rails` (with a `-`, not an `_`).

**Comment by Rehankhan100** [comment]
thanks @Deckluhm when i restart my server everything works fine.
