### ISSUE TITLE
// @import 'motion-ui'; not working

### ISSUE THREAD

**Issue by computalya** [zurb/foundation-rails#148]
in foundation_and_overrides.scss I had to use

`@import 'motion-ui/motion-ui';` 

instead of

` @import 'motion-ui';` 

error message was:

> File to import not found or unreadable: motion-ui.

**Comment by zokioki** [comment]
What version of the gem are you using? 

Starting from 6.1.1.3, `foundation_and_overrides.scss` is generated with `@import 'motion-ui/motion-ui` commented out, once `rails g foundation:install` is run - [see here](https://github.com/zurb/foundation-rails/blob/d94979f4f99727dd2a730dac375ee2f5c6e5545c/lib/generators/foundation/templates/foundation_and_overrides.scss#L8).

**Comment by computalya** [comment]
I have updated from 6.1.1.1 to 6.1.2.0 with 

`bundle update`

but forget to re-run

`rails g foundation:install`

thanks
