### ISSUE TITLE
Support for Foundation Apps (v6)

### ISSUE THREAD

**Issue by bsodmike** [zurb/foundation-rails#151]
Hi all,

Are there any plans to support Foundation Apps as well?
http://foundation.zurb.com/apps.html

Thanks!

**Comment by silverstorm** [comment]
:+1:

**Comment by bsodmike** [comment]
Perhaps we could add `//= require foundation/apps` into the JS manifest, and similarly namespace SCSS accordingly.  Thoughts?

**Comment by Yanchek99** [comment]
:+1:

**Comment by zokioki** [comment]
AFAIK, there are currently no plans to officially support a gem version of Foundation Apps. You may be able to gemify the Foundation for Apps assets via [RailsAssets](https://rails-assets.org) and include them inside your Rails apps that way.
