### ISSUE TITLE
Javascript hidden submit button shows on size chage

### ISSUE THREAD

**Issue by anthonymidili** [zurb/foundation-rails#153]
I have a select year in the top bar with a hidden submit button.
```
$(document).on 'ready page:load', ->

  $(".hide_and_submit input[type='submit']").hide()
  $('.hide_and_submit').change ->
    $(this).closest('form').submit()
    return
```
When the responsive-menu toggles to small and the menu icon appears this CoffeeScript breaks and shows the hidden submit button only in the top bar. This CoffeeScript  works fine for other hide_and_submit forms in my app.

**Comment by mehlah** [comment]
This repo is programmatically generated based on tagged releases to the main Foundation for Sites repo.
If your issue is still relevant, please open it in the main repo https://github.com/zurb/foundation-sites
Thanks!
