### ISSUE TITLE
OFFCANVAS DEFAULT POSITION

### ISSUE THREAD

**Issue by lethunder** [zurb/foundation-rails#154]
Hello,
i upgraded to foundation 6. i can't set the default position of offcanvas to open. Can anyone help? please 
thanks in advance

**Comment by mehlah** [comment]
This repo is programmatically generated based on tagged releases to the main Foundation for Sites repo.
If your issue is still relevant, please open it in the main repo https://github.com/zurb/foundation-sites
Thanks!
