### ISSUE TITLE
OFFCANVAS BUTTON

### ISSUE THREAD

**Issue by lethunder** [zurb/foundation-rails#155]
Hello,
i recently migrate to foundation 6 but i have some issues. For exemple, i have an offcanvas inside another offcanvas. when i click on my menu-icon button to toggle the first offcanvas left menu it also triggers the left menu on the other offcanvas. both get opened.

**Comment by mehlah** [comment]
This repo is programmatically generated based on tagged releases to the main Foundation for Sites repo.
If your issue is still relevant, please open it in the main repo https://github.com/zurb/foundation-sites
Thanks!
