### ISSUE TITLE
Dropdown's are not being displayed properly.

### ISSUE THREAD

**Issue by calderJamNet** [zurb/foundation-rails#156]
I made a brand new rails project to test it out and its still not working as it is when I open the index page in the foundation source folder.

[Here it is in rails](http://imgur.com/7yMEN6z)

[And here run from foundations source folder](http://imgur.com/9JRMD6x)

I've already removed turbolinks from the project so that should not be the issue.

**Comment by decabeza** [comment]
@calderJamNet can you paste your HTML code? 

I have some little issues with some foundation 6 elements, maybe I can help you :wink:

**Comment by calderJamNet** [comment]
thanks @decabeza! Here you go:

`<div class="top-bar">
  <div class="row">
    
    <div class="top-bar-title"><%= image_tag 'logo.png', alt: 'JamNet', id: 'logo' %></div>
    <div class="top-bar-left">
      <ul class="menu">
        <li><input class="topSearch" type="search" placeholder="Search"></li>
        <li><button type="button" class="button searchButton"><a class="fa fa-caret-down searchCaret"></a></button></li>
      </ul>
    </div>
    
    <div class="top-bar-right">
      
      <ul class="dropdown menu topbarIcons" data-dropdown-menu>
        <li><a href="#"><i class="fi-alert"></i></a></li>
        <li><a href="#"><i class="fi-comment"></i></a></li>
        <li><a href="#"><i class="fi-torsos"></i></a></li>
        <li class="has-submenu">
          <a class="fa fa-caret-down smallCaret"></a>
          <ul class="submenu menu vertical topbarDrop" data-submenu>
            <li><a href="#">New Project</a></li>
            <li><a href="#">New Event</a></li>
            <li><a href="#">Help</a></li>
            <br>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="top-bar-right">
      
      <ul class="menu topbarLinks">
        <li class="linkHome"><a href="#">Home</a></li>
        <li class="linkEvents"><a href="#">Events</a></li>
        <li class="linkProfile"><a href="#">Profile</a></li>
      </ul>
    </div>
  </div>
</div>`

**Comment by decabeza** [comment]
@calderJamNet I think I found the solution! You must to include **"align-right"** class to "ul.menu", and change the li orders on HTML. This results:

![screen shot 2016-02-06 at 11 01 02](https://cloud.githubusercontent.com/assets/631897/12866108/b8e9d8a0-ccc1-11e5-8cd9-071dc2f29f72.png)

I hope helps you!  :wink: 

```
<ul class="dropdown menu align-right topbarIcons" data-dropdown-menu>
    <li class="has-submenu">
        <a class="fa fa-caret-down smallCaret"></a>
        <ul class="submenu menu vertical topbarDrop" data-submenu>
            <li><a href="#">New Project</a></li>
            <li><a href="#">New Event</a></li>
            <li><a href="#">Help</a></li>
            <br>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Logout</a></li>
        </ul>
    </li>
    <li><a href="#"><i class="fi-alert"></i></a></li>
    <li><a href="#"><i class="fi-comment"></i></a></li>
    <li><a href="#"><i class="fi-torsos"></i></a></li>
</ul>
```

**Comment by calderJamNet** [comment]
That worked! Thanks a lot @decabeza, I had tried including align-right but in the submenu, so I guess that was my problem.

**Comment by decabeza** [comment]
:tada:
