### ISSUE TITLE
Error on installing with Rails 5 Beta2

### ISSUE THREAD

**Issue by SylarRuby** [zurb/foundation-rails#158]
Im using foundation 6.

After `rails g foundation:install`:

```
sylar$ rails g foundation:install
      insert  app/assets/javascripts/application.coffee
/Users/sylar/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/sylar/Sites/rails/rails5/demo/app/assets/javascripts/application.coffee (Errno::ENOENT)
```

**Comment by Deckluhm** [comment]
You don't have any javascript manifest (`app/assets/javascripts/application.[js/coffee]`), do you?

I just tested it with rails `5.0.0.beta2` / foundation-rails `6.1.2.0` and it works perfectly.

**Comment by bsodmike** [comment]
@Deckluhm perhaps the generator should check if `application.coffee` exists first; unless it should by default.

**Comment by Deckluhm** [comment]
This file exists in any new Rails app but you can delete it / rename it / choose not to use it.

One solution is to change the installer and prompt the user to choose the file he wants to use.
Another one is to follow the [manual installation instructions](https://github.com/zurb/foundation-rails#manual-installation).

**Comment by openscript** [comment]
If you want to use foundation-rails in a Rails 5 engine you have the same problem. The manifest file is in a sub folder. The sub folder is named after the engines name.

The foundation installer is looking for a file at `./app/assets/javascripts/application.coffee` but it is actually at `./app/assets/javascripts/enginename/application.coffee`.

**Comment by SylarRuby** [comment]
Hi guys. Nothing was working so I head back to rails 4.
