### ISSUE TITLE
Issue with closing reveal window

### ISSUE THREAD

**Issue by arsen91** [zurb/foundation-rails#160]
I'm struggling with getting work reveal using your gem. While has all the same code, on documentations page of foundation itself reveal works fine, but not on my rails page. I gave the following code in my html.slim:

    .reveal#exampleModal1 data-reveal='data-reveal'
        h1 Awesome. I Have It.
        p.lead Your couch. It is mine.
        p I'm a cool paragraph that lives inside of an even cooler modal. Wins!
        button.close-button data-close="data-close" aria-label="Close modal" type="button"
           span aria-hidden="true"&times;

and the link itself:

`a.add-reveal data-open="exampleModal1" Open reveal`

When I click the link, reveal is opened, but styles are not correct - the reveal is too wide.
The if I try to close the window with close button, it does't work. I click outside of the reveal and window closes. If I open it again, the second time without reloading the page, I can see correct width of the reveal, but close button still doesn't work. 

Whatever I do, close button still doesn't work. As stated [here](https://github.com/zurb/foundation-rails/issues/138), I've added motion-ui through @import. Rails doesn't tell me that it's not found, so I come to conclusion - it's installed. 

Probably it's not the issue with the gem itself, but I can't guess the root of the issue, so starting here.. Thanks

**Comment by Deckluhm** [comment]
Just change: 
- `data-reveal='data-reveal'` to `data-reveal=''` (or `data-reveal=true`)
- `data-close='data-close'` to `data-close=''` (or `data-close=true`)

**Comment by arsen91** [comment]
Perfect! Such an easy thing! 
However I still have an issue with sizing. The first time it's opened, the modal is too wide. The second time - it's of the default size - 600px. Surely I can add a handler on opening the window and change styles by myself, but not sure it's a right thing to do.. 
Any idea on that?

**Comment by mehlah** [comment]
@arsen91 are you still seeing this issue as related to foundation-rails and not foundation itself?

**Comment by arsen91** [comment]
This might be not gem's fault.. I tried with pure foundation and also faced issues. I think you can close this stream. Thank you

**Comment by mehlah** [comment]
:kissing:
