### ISSUE TITLE
Reveal won't open again after clicking link inside the modal.

### ISSUE THREAD

**Issue by mightystrong** [zurb/foundation-rails#164]
I'm using a modal as a full screen menu. 

```html
<div class="full reveal text-center" id="modal-nav" data-reveal data-show-delay="500" data-hide-delay="500">
  <h1>menu</h1>
  <%= link_to "Home", root_path %>
  <button class="close-button" data-close aria-label="Close reveal" type="button">
    <span aria-hidden="true">close</span>
  </button>
</div>
```

with the following link:

```html
<section class="home-menu">
  <div class="row align-middle">
    <p><a data-toggle="modal-nav">Modal test</a></p>
  </div>
</section>
```
Everything works fine until I click on the "Home" link in the modal. When I get back to the home screen, the modal no longer works. I've tried disabling turbolinks but that wasn't the source of the problem. Any recommendations?

Thanks

**Comment by Deckluhm** [comment]
Any error in JS console?

Are you sure the modal is also included in the homepage?

**Comment by mightystrong** [comment]
Unfortunately, no error in the JS console. I'm loading the modal as a partial so it's available throughout the app. It's almost as if the foundation javascript didn't load properly after clicking the link. I used to solve this with issue with the following in Foundation 5 in my application.rb file. 
```javascript
$(function(){ $(document).foundation('alert','events'); });
```
Tried the same in the new app but it appears this has been deprecated as I get a console error message.

**Comment by Deckluhm** [comment]
Maybe check if Foundation is initialized by typing `Foundation` in your browser's console?

**Comment by mightystrong** [comment]
It is.

Michael Price
Mighty Strong Media
202-445-4510 / 720-515-7581
mike@mightystrongmedia.com
@MightyStrongly

**Comment by Deckluhm** [comment]
If it appears to be a Foundation issue, I doubt it is a related to the gem. You should have posted this issue in the [framework repository](github.com/zurb/foundation-sites).

You should try to isolate your code in a [CodePen](http://codepen.io/pen/) to see if it's a Foundation issue or if it is related to your code.

If you need help to resolve your issue, please show more code (view and corresponding JS loaded in this page).

**Comment by mightystrong** [comment]
Thanks. Will do.

**Comment by mehlah** [comment]
I'm closing this as it doesn't seems to be related to foundation-rails gem.
Thanks :kissing:
