### ISSUE TITLE
Add $foundation-pallete to _settings.scss

### ISSUE THREAD

**Issue by dsandstrom** [zurb/foundation-rails#166]
Some items don't use the `$primary-color` assigned in the settings. They required a explicit `$foundation-palette`.

Adding
```
$foundation-palette: (
  primary: $primary-color,
  secondary: $secondary-color,
  success: $success-color,
  warning: $warning-color,
  alert: $alert-color
);
```
at the bottom **1. Global** fixed issues for me.

https://github.com/zurb/foundation-sites/issues/8281

**Comment by zokioki** [comment]
Addressed by #167. Will be available in the 6.2.0.1 release. Closing :+1:

**Comment by zokioki** [comment]
v6.2.0.1 has been [released](https://github.com/zurb/foundation-rails/releases/tag/v6.2.0.1)

**Comment by dsandstrom** [comment]
Thanks for the quick update.

Do I need to do something special to get `rake assets:update`?  I don't have that task.

**Comment by dsandstrom** [comment]
I thought the release note was saying to run the rake task to update the settings file in our app's assets.  I figured it was something like the generator that merges in the changes.  However, it seems like we have to manually merge in the changes from the gem's settings file.
