### ISSUE TITLE
Off Canvas not working on ios 8.1

### ISSUE THREAD

**Issue by phil9690** [zurb/foundation-rails#168]
The off canvas doesn't seem to work on IOS 8.1 with Chrome version 31 and Safari version 8. It shows the transparent overlay, but not the toggled content.

If I go to http://foundation.zurb.com/sites/docs/off-canvas.html, the examples work, but it won't work with the gem. I have tested it in IOS 9 with the latest versions of Chrome and Safari, and Ubuntu with Chrome and Mozilla. It works fine with all of these.

I've tried disabling turbolinks and starting with a new app using examples from the off canvas docs, but I still can't get it to work in IOS 8. There are no errors in the JS console and I'm using the latest gem version 6.2.0.1

Does anyone know what could be causing this issue?

Thanks

**Comment by hellapixels** [comment]
Hey phil9690,

Sorry you are having some issues with this component. Does it work in other browsers? If not, I think it might have to do with Motion UI not being included. If you go to foundation_and_overrides.scss you will need to un-comment the 3 motion ui files:

@import 'motion-ui/motion-ui';
@include motion-ui-transitions;
@include motion-ui-animations;

We are going to include it by default here soon.

**Comment by panigrah** [comment]
This gem did not work with the examples posted here http://foundation.zurb.com/sites/docs/off-canvas.html. I had to explicitly call offCanvas like below. Is this how i need to use offcanvas?

        $(document).ready( function() {
           $(document).foundation().ready(function() {
              var OffCanvas = new Foundation.OffCanvas($('#offCanvasLeft'), {
              open_method : 'overlap' ,
              close_on_click : true
             });
          })
       });

**Comment by zokioki** [comment]
@panigrah You shouldn't have to explicitly call offCanvas if the page has the correct markup for it to work. I'll look into why this issue is occurring.

**Comment by krismartin** [comment]
I'm experiencing the same issue on iOS6.1.3 (with Safari on iPad). It shows the transparent overlay, but not the off canvas menu. I tried including the Motion UI as suggested by @hellapixels, but it didn't work. The solution that @panigrah gave also didn't work. Any update on this?

**Comment by unsullen** [comment]
I am also experiencing this issue with foundation 6.2.3. In both Chrome and Safari on iOS 8 or below, the off-canvas menu does not display, but the js-off-canvas-exit overlay does. in iOS 9 everything works as expected on both browsers.

My SCSS includes both Motion UI transitions and transforms.

Unfortunately iOS 8 still makes up a significant enough portion of my site visitors to make this a problem. Is this still considered an open issue and a fix is being looked at?

**Comment by kevindoocey** [comment]
Was this issue ever fixed? Still facing the problems as the folks above; the overlay showing, but no menu in sight - just on certain iOS devices. All other mobiles, and iPhone 7 works fine.

**Comment by leejacksonltd** [comment]
I found older safari needed -webkit- to work:

`.position-left {
	-webkit-transform:translateX(-250px)
}

.position-left.is-open~.off-canvas-content {
	-webkit-transform:translateX(250px)
}

.off-canvas.is-open {
	-webkit-transform:translateX(0px)
}`

**Comment by ifatree** [comment]
still an issue on Safari 8 desktop as well. you can see it on the foundation homepage that the off-canvas also doesn't have -webkit-transform properties. this makes it show by default and not be able to be hidden... but once you get into the example documentation for off-canvas menus with buttons to open them on the page, it has -webkit-transform properties there.  very weird it's not in the default set. use browswerstack on Yosemite (Safari 8) to see the same issue on the homepage of foundation.

**Comment by mlangone** [comment]
@ifatree I am having a similar issue, did you ever find a fix? Off canvas loads as open and won’t  dismiss.

**Comment by ncoden** [comment]
> If I go to http://foundation.zurb.com/sites/docs/off-canvas.html, the examples work, but it won't work with the gem. I have tested it in IOS 9 with the latest versions of Chrome and Safari, and Ubuntu with Chrome and Mozilla. It works fine with all of these.

`foundation-rails` uses the `foudation-sites` JavaScript and CSS assets. Unless with an issue with Turbolink, there should be no bug in a Rails application that cannot be reproduced in the documentation. It comes from the outdated Foundation version in this package, which has been bumped to `v6.4.3` recently.

Closing. Please reopen [on the right repo](https://github.com/zurb/foundation-sites) if you can reproduce it with Foundation `v6.4.3`.
