### ISSUE TITLE
Update to version 6

### ISSUE THREAD

**Issue by hmihail** [zurb/foundation-rails#170]
How do I update to version 6? I tried `bundle update` but it remained to version 5.5.3.

Thanks!

**Comment by zokioki** [comment]
You can try specifying a version in the gemfile, like so:

    gem 'foundation-rails', '~> 6.1'

Then run `bundle update foundation-rails`

Hope that helps!

**Comment by zokioki** [comment]
Closing. Feel free to reopen if you're still having issues with this.
