### ISSUE TITLE
Color variables conflict

### ISSUE THREAD

**Issue by justinj656** [zurb/foundation-rails#173]
In **_setting.scss** below variables are set.
```scss
// line 50 - 54
$primary-color
$secondery-color
$success-color
$warning-color
$alert-color
```

Also in **_global.scss**, these variables are reset.
```scss
...
//  line35 - 31
$foundation-palette: (
  primary: #2199e8,
  secondary: #777,
  success: #3adb76,
  warning: #ffae00,
  alert: #ec5840,
) !default;
...
// line 106 - 110
$primary-color: map-get($foundation-palette, primary);
$secondary-color: map-get($foundation-palette, secondary);
$success-color: map-get($foundation-palette, success);
$warning-color: map-get($foundation-palette, warning);
$alert-color: map-get($foundation-palette, alert);
...
```

And in **foundation_and_overrides.scss**
```scss
@import 'settings';
@import 'foundation';
```
**foundation.scss** then import **_global.scss**.

Therefore, the custom color values set by me in **_setting.scss** only work within **_setting.scss**. Then colors are restored to the default value, which causes inconsistence.

To solve this, at present, I have to maintain an additional $foundation-palette in **_setting.scss** with the same color values of those variables such as $primary-color etc.

**Comment by Deckluhm** [comment]
It works this way since `6.2`, please take a look at my comment for a full explanation: https://github.com/zurb/foundation-sites/issues/8281#issuecomment-190306538

I hope this helps!

**Comment by mehlah** [comment]
Closing this.
Thanks @Deckluhm
