### ISSUE TITLE
Modal Not Closing in  a React Component

### ISSUE THREAD

**Issue by SylarRuby** [zurb/foundation-rails#178]
I am using Rails 4.2.5 with React. I can open the modal but the close button wont close the modal. It only closes with the `esc` key and if I click the image. Any ideas?

````
<div className="full reveal global-centered" id={q.id} data-reveal>
  <br />
  <img data-toggle={q.id} src={q.evidence_url} />
  <button className="close-button" data-close aria-label="Close reveal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

````

**Comment by gwynevans** [comment]
Try changing `data-close` and `data-reveal` to `data-close=""` and `data-reveal=""`.

Just come across this in "The Complete React Web App Developer Course" Udemy course by Andrew Mead, but I'm not yet clear as to exactly what it's doing...

**Comment by SylarRuby** [comment]
@gwynevans Cool. I'll have a go later. Thanks.

**Comment by SylarRuby** [comment]
@gwynevans It's been awhile. Works. Thanks.
