### ISSUE TITLE
rails g foundation:install command doesn't produce full list of components in foundation_and_overrides file

### ISSUE THREAD

**Issue by mifrej** [zurb/foundation-rails#179]
So as in subject....
In foundation_and_overrides.scss after installing foundation in rails there should be all components uncommented.
But I found one missing `@include foundation-menu-icon;`
This took me couple hours to find out why the hamburger menu doesn't show up.
I didn't suspect this place to be affected as the comment says:
`// We include everything by default.`
Would you please check the generator or whatever to produce the real full list of components in the final settings file.
Thank you in advance!

**Comment by garshyn** [comment]
+1
`@include foundation-flex-classes;` is also missing

**Comment by akaspick** [comment]
👍 Please fix the .scss file with the proper includes and the proper order.
