### ISSUE TITLE
enabling Flexbox Mode gives an ActionView::Template::Error

### ISSUE THREAD

**Issue by addstar34** [zurb/foundation-rails#181]
Using Foundation 6.2.0.1 installed via Gem, I enable flex box as per the documentation and my site won't load. It's getting stuck loading application.css.scss.

_settings.scss
`$global-flexbox: true;`

foundation_and_overrides.scss
`// @include foundation-grid; `
`@include foundation-flex-grid; `
`@include foundation-flex-classes; `

returns the following error:

> ActionView::Template::Error (Properties are only allowed within rules, directives, mixin includes, or other properties.):
     6:
     7:     <title><%= content_for?(:title) ? yield(:title) : "Title" %></title>
     8:
     9:     <%= stylesheet_link_tag    "application" %>
    10:     <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    11:     <%= csrf_meta_tags %>
  app/views/layouts/application.html.erb:9:in `_app_views_layouts_application_html_erb__73442163__584527848'

**Comment by addstar34** [comment]
Further investigation seems that the setting of `$global-flexbox: true;` in `_settings.scss` is the main cause of the problem.

If I set this to false but leave `@include foundation-flex-grid;` and `@include foundation-flex-classes;` the site will load.

I also reordered the includes as was mentioned here: [https://github.com/zurb/foundation-sites/issues/8278](url)

**Comment by addstar34** [comment]
Upon further investigation I found enabling flexbox mode as per the documentation [http://foundation.zurb.com/sites/docs/flexbox.html](url)

Then, if I comment out `@include foundation-top-bar` assets are compiled and the site loads.

Looking at localhost:3000/assets/application.css I can see `display: flex` is set for numerous things but obviously top-bar is missing.

So it appears the error lines within _top_bar.scss.

**Comment by victorsosa** [comment]
you are right; there is an open issue https://github.com/zurb/foundation-sites/issues/8325 for this

**Comment by mehlah** [comment]
I'm closing this as not related to foundation-rails.
Thanks :kissing:
