### ISSUE TITLE
What is the current version and docs?

### ISSUE THREAD

**Issue by mjacobus** [zurb/foundation-rails#184]
Hi guys

I can see now the gem version is 6.2.something. Is that the version of the css/js framework?

It would be very simple and useful to make it clear on the readme, as well as add a link to the documentation.

Right now I am using [this](http://foundation.zurb.com/sites/docs/top-bar.html) documentation but as the page is not looking very good I am wondering if I packed the correct assets version in my app.

Cheers!

**Comment by patricklindsay** [comment]
Yes it is the same version. The gem is kept up to date with the foundation framework and so the versions are kept in sync. There is a link to the documentation at the bottom of the README.

If you have followed the proper installation steps I'm not sure why you would be having a problem. Try posting a code snippet along with a screenshot detailing the problem.

**Comment by mjacobus** [comment]
True, the link is at the bottom. I had missed that.

Thank you @patricklindsay =)
