### ISSUE TITLE
Tab callback is not working

### ISSUE THREAD

**Issue by tejashande** [zurb/foundation-rails#186]
I have implemented tab in my app & rest of the things work properly.

But my tab callback doesn't seems to be called.

This is what I tried in application.js

```
$('[data-tabs]').on('toggled', function (event, tab) {
  console.log(tab);
});
```

& this gave error in firebug

```
$(document).foundation({
  tab: {
    callback : function (tab) {
      console.log(tab);
    }
  }
});
```

Is their any other callback for tabs in foundation? Any help or suggestion will be appreciated.

**Comment by saxton-tad** [comment]
I don't think you're listening to the right event:

    $('#my-tabs').on('change.zf.tabs', function() {
      // do something with tab change
    })
