### ISSUE TITLE
Sprockets method 'register_engine' is deprectated

### ISSUE THREAD

**Issue by gvescu** [zurb/foundation-rails#196]
Any rake task or rails generator throws this warning when including `foundation-rails` on my Gemfile.

```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from <module:Sprockets> at C:/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-es6-0.9.0/lib/sprockets/es6.rb:90)
```

It happens even on the latest 6.2.3.0.

**Comment by therise3107** [comment]
I am experiencing the same issue , although i have tried updating gems and installing latest sprockets

**Comment by xinspire** [comment]
Update the gems `sprockets-es6` and `sass-rails` and the messages should go away.

I updated mine from 0.9.0 to 0.9.2 and 5.0.3 to 5.0.6, respectively.

**Comment by ncoden** [comment]
Closing as this issue is already resolved.
