### ISSUE TITLE
Where is the alert-box?

### ISSUE THREAD

**Issue by ringe** [zurb/foundation-rails#200]
Seems like alert-box is left out of this gem. Fresh install of Rails 5 with Foundation 6.

**Comment by zokioki** [comment]
Alert boxes and panels from Foundation 5 have been combined to form the Callout component - [see Docs](http://foundation.zurb.com/sites/docs/callout.html).

Here's an example of creating a callout box in Foundation 6:

```html
<div class="success callout" data-closable>
  <h5>This a friendly message.</h5>
  <p>And when you're done with me, I can be closed using a Motion UI animation.</p>
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
```
