### ISSUE TITLE
util/util not found or unreadable

### ISSUE THREAD

**Issue by Rcurran** [zurb/foundation-rails#206]
Followed the installation instructions and after running rails g foundation:install I get 

File to import not found or unreadable: util/util.

A quick search on Google shows this is a common issue, I've literally just run into it in a clean rails 5 / ruby 2.3.1 project. Presumably there is something missing from the installation guide. I'll explore this and probably fix it in five minutes but the issue remains for new users who will end up in the same boat. 

Worth a mention.

**Comment by Rcurran** [comment]
I apologise, I only had to restart the rails server to fix the issue. This issue isn't an issue.

**Comment by amicming** [comment]
@Rcurran, Thanks - after  restart the rails server, working fine.
