### ISSUE TITLE
Rails5, foundations-rails, Turbolinks 5 issues

### ISSUE THREAD

**Issue by beauraF** [zurb/foundation-rails#211]
Hi everyone,

I encounter many problems with the `top-bar` and `dropdown` components. 
First of all, I use Rails5, Turbolink5 and the last foundation-rails.
The entire HTML code that I will use is from the official documentation : http://foundation.zurb.com/sites/docs/top-bar.html

### Problem with `top-bar-right` and `top-bar-left` and `top-bar-title` :

**HTML :**
```
<div class="top-bar">
  <div class="top-bar-title">Title</div>
  <div>
    <div class="top-bar-left">Left</div>
    <div class="top-bar-right">Right</div>
  </div>
</div>
```
**Result :** 
![capture d ecran de 2016-11-28 21-33-25](https://cloud.githubusercontent.com/assets/12185788/20694372/b29d48ee-b5b2-11e6-84d5-ee09a141c368.png)

### Problem with `dropdown` :

My `dropdown menu` are always open and react oddly when clicked on.

**HTML :** 
```
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Site Title</li>
      <li>
        <a href="#">One</a>
        <ul class="menu vertical">
          <li><a href="#">One</a></li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </li>
      <li><a href="#">Two</a></li>
      <li><a href="#">Three</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
  </div>
</div>
```

**Result :**
![capture d ecran de 2016-11-28 21-40-40](https://cloud.githubusercontent.com/assets/12185788/20694550/fc1462f4-b5b3-11e6-8123-3bd267059e7c.png)
![capture d ecran de 2016-11-28 21-44-51](https://cloud.githubusercontent.com/assets/12185788/20694553/fed26a90-b5b3-11e6-939b-c2217a649d98.png)

I have already tried a lot of solution found on the net (jquery.turbolinks, turbolinks2.4.3, turbolinks-compatibility.coffee), nothing work.

If someone have other solution to proposed, I thank him in advance.
Thank you for your time.

**Comment by murdoch** [comment]
What is in your application.js file?

**Comment by beauraF** [comment]
Thank you for your answer, but I am using another framework. :)
I forgot to close the issue.

Have a nice day.
