### ISSUE TITLE
foreground() causes error in 6.3.0 gem upgrade

### ISSUE THREAD

**Issue by wrburgess** [zurb/foundation-rails#214]
Upgrading to 6.3.0.0 of this gem breaks due to changes in the Foundation 6.3.0 upgrade

## How can we reproduce this bug?

* Using `Ruby 2.3.3`
* Using `Rails 5.0.1`
* Upgrade to `foundation-rails 6.3.0.0` in your `Gemfile`:
* Run `bundle update`

Example:

```ruby
# Gemfile

gem "foundation-rails", "6.3.0.0"
```

Run a process that requires a recompilation of scss files (in my case, a test with RSpec)

## What did you expect to happen?
There should not be an error message

## What happened instead?
```
     ActionView::Template::Error:
       $color: "foreground(#2199e8)" is not a color for `red'
     # ./app/assets/stylesheets/foundation_and_overrides.scss:30
```

## Other information

I'm not sure what I'm supposed to do to accomodate these changes, but I think the problems point back to these changes:

https://github.com/zurb/foundation-sites/pull/9319#issuecomment-263414697

## Temporary Fix

I commented out the `// @include foundation-badge;` and `// @include foundation-label;` lines in the `foundation_and_overrides.scss` file and things started working again

**Comment by Deckluhm** [comment]
It's a breaking change listed in the [`6.3` release notes](https://github.com/zurb/foundation-sites/releases/tag/v6.3.0):

> The default color palette has changed to be meet AA contrast requirements. This has changed both defaults and a number scss variables and functions. Check out [#9319 (comment)](https://github.com/zurb/foundation-sites/pull/9319#issuecomment-263414697)

Following the comment, you can see that the `foreground()` function has been replaced by a `color-pick-contrast()` function (which works slightly differently):

> The `foreground()` function has been replaced with a new `color-pick-contrast()` function that uses luminosity instead of lightness.

> All instances of the foreground() function have removed from _settings.scss in favor of setting explicit colors and alternate colors.

So I think you should just use `color-pick-contrast()` function, an explicit color or create your own function if it doesn't fit your needs.

**Comment by wrburgess** [comment]
For anyone with this same issue, try these commands:

* Note: back up any customizations made to `_settings.scss`
* Note: better yet, create a new branch for this update, first!

1. Change this line in your Gemfile:

```ruby
gem "foundation-rails", "6.2.4.0"
```
to  

```ruby
gem "foundation-rails", "6.3.0.0"
```

1. Command `bundle install`
1. Command `rails g foundation:install`
1. Reply `n` for all Overwrite permissions, except `Y` for overwriting `app/assets/stylesheets/_settings.scss`

* Note: These steps will allow for the replacement of the `foreground()` function that breaks in foundation-rails 6.3.0.0

**Comment by Deckluhm** [comment]
Note that this will overrides any customization previously made to `_settings.scss` (and that's probably not what most people wants).

Sadly there is no easy way to update the `_settings.scss`.

**Comment by ringe** [comment]
Breaking changes always means side effects.
I solved this by removing _settings.scss and foundation_and_overrides.scss

Obviously not the preferred way to fix it. But I am in the middle of development, so the side effects are minimal for me.
