### ISSUE TITLE
Spec tests do not run because issue with Rails 5 engine

### ISSUE THREAD

**Issue by Yanchek99** [zurb/foundation-rails#220]
Receive the following error when running spec from stock check out
`There was an error while trying to load the gem 'foundation-rails'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `squish' for #<String:0x007fc1e19b11d0>`

This is due to an issue with the line `isolate_namespace Foundation::Rails` in the  engine.rb file.  I am stumped as to what the possible fix is however I don't think this gem was built for a Rails 5 test bed.  But some further investigation is needed to determine the exact cause of the issue.

Simple workaround fix is to change the gemspec file to `spec.add_development_dependency "rails", "4.2.8"`

**Comment by bbuchalter** [comment]
@Yanchek99 did you ever figure out what was going on here? I am experiencing the same issue in a different engine but haven't seen many reports of the problem.

**Comment by Yanchek99** [comment]
@bbuchalter I never had the time to dig that deep, it was just something I noticed and wanted to track it.

**Comment by ncoden** [comment]
This doesn't seem to be related to Foundation. See https://github.com/bbuchalter/solidus_lograge/commit/d4ebcb242d182540af899636c879806e5d28f944. Closing.
