### ISSUE TITLE
File to import not found or unreadable: util/util.

### ISSUE THREAD

**Issue by svillegascreative** [zurb/foundation-rails#221]
Immediately upon installation:

> Extracted source (around line # 44):
> ```
> //  37. Top Bar
> 
> @import 'util/util';
> 
> // 1. Global
> // ---------
> ```              

I can get by by commenting it out. There is no util folder or file... Safe to delete, or...?

**Comment by svillegascreative** [comment]
Actually all of my @imports and @includes seem to be failing...

**Comment by Deckluhm** [comment]
We will need more information to help you.

Can you do a `bundle list` and show us the output?

**Comment by svillegascreative** [comment]
n/m. A few hours of frustrated Googling tipped me off to reset the server. All good now. Maybe worth a mention in the readme?

**Comment by Deckluhm** [comment]
That's just how Rails works: after installing / updating gems you should restart your server.

**Comment by sergibeltran** [comment]
The same problem here, I've reseted my rails server immediately upon installation .

Actually all of my @imports and @includes seem to be failing like @svillegascreative said.

My bundle list:
  * actioncable (5.0.2)
  * actionmailer (5.0.2)
  * actionpack (5.0.2)
  * actionview (5.0.2)
  * activejob (5.0.2)
  * activemodel (5.0.2)
  * activerecord (5.0.2)
  * activesupport (5.0.2)
  * addressable (2.5.1)
  * arel (7.1.4)
  * babel-source (5.8.35)
  * babel-transpiler (0.7.0)
  * bindex (0.5.0)
  * builder (3.2.3)
  * bundler (1.14.6)
  * byebug (9.0.6)
  * capybara (2.13.0)
  * childprocess (0.6.3)
  * coffee-rails (4.2.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.12.2)
  * concurrent-ruby (1.0.5)
  * database_cleaner (1.5.3)
  * diff-lcs (1.3)
  * erubis (2.7.0)
  * execjs (2.7.0)
  * factory_girl (4.8.0)
  * factory_girl_rails (4.8.0)
  * ffi (1.9.18)
  * foundation-rails (6.3.1.0)
  * globalid (0.3.7)
  * haml (4.0.7)
  * i18n (0.8.1)
  * jbuilder (2.6.3)
  * jquery-rails (4.3.1)
  * listen (3.0.8)
  * loofah (2.0.3)
  * mail (2.6.4)
  * method_source (0.8.2)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mini_portile2 (2.1.0)
  * minitest (5.10.1)
  * multi_json (1.12.1)
  * nio4r (2.0.0)
  * nokogiri (1.7.1)
  * public_suffix (2.0.5)
  * puma (3.8.2)
  * rack (2.0.1)
  * rack-test (0.6.3)
  * rails (5.0.2)
  * rails-controller-testing (1.0.1)
  * rails-dom-testing (2.0.2)
  * rails-html-sanitizer (1.0.3)
  * railties (5.0.2)
  * rake (12.0.0)
  * rb-fsevent (0.9.8)
  * rb-inotify (0.9.8)
  * rspec-core (3.5.4)
  * rspec-expectations (3.5.0)
  * rspec-mocks (3.5.0)
  * rspec-rails (3.5.2)
  * rspec-support (3.5.0)
  * rubyzip (1.2.1)
  * sass (3.4.23)
  * sass-rails (5.0.6)
  * selenium-webdriver (3.3.0)
  * spring (2.0.1)
  * spring-watcher-listen (2.0.1)
  * sprockets (3.7.1)
  * sprockets-es6 (0.9.2)
  * sprockets-rails (3.2.0)
  * sqlite3 (1.3.13)
  * thor (0.19.4)
  * thread_safe (0.3.6)
  * tilt (2.0.7)
  * turbolinks (5.0.1)
  * turbolinks-source (5.0.0)
  * tzinfo (1.2.3)
  * uglifier (3.2.0)
  * web-console (3.5.0)
  * websocket (1.2.4)
  * websocket-driver (0.6.5)
  * websocket-extensions (0.1.2)
  * xpath (2.0.0)

File to import not found or unreadable: util/util...

What can I do?

**Comment by Deckluhm** [comment]
> What can I do?

Give us more info? :D

Can you show us your CSS manifest? (`app/assets/stylesheets/application.css` by default)

**Comment by sergibeltran** [comment]
Yes ;)

These are my steps:

Added to Gemfile
`gem 'foundation-rails'`
Run commands:
`bundle install`
`rails g foundation:install`

app/assets/stylesheets/application.css (tried with scss extension too)
```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or any plugin's vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any other CSS/SCSS
 * files in this directory. Styles in this file should be added after the last require_* statement.
 * It is generally better to create a new file per style scope.
 *
 *= require_tree .
 *= require_self
 *= require foundation_and_overrides

 */
```

app/assets/stylesheets/_settings.scss (this file is 600 lines long, I show you which line breaks)
```
@import 'util/util';
```

app/assets/stylesheets/foundation_and_overrides.scss
```
@charset 'utf-8';

@import 'settings';
@import 'foundation';

// If you'd like to include motion-ui the foundation-rails gem comes prepackaged with it, uncomment the 3 @imports, if you are not using the gem you need to install the motion-ui sass package.
//
// @import 'motion-ui/motion-ui';

// We include everything by default.  To slim your CSS, remove components you don't use.

@include foundation-global-styles;
@include foundation-grid;
@include foundation-typography;
@include foundation-button;
@include foundation-forms;
@include foundation-visibility-classes;
@include foundation-float-classes;
@include foundation-accordion;
@include foundation-accordion-menu;
@include foundation-badge;
@include foundation-breadcrumbs;
@include foundation-button-group;
@include foundation-callout;
@include foundation-card;
@include foundation-close-button;
@include foundation-drilldown-menu;
@include foundation-dropdown;
@include foundation-dropdown-menu;
@include foundation-responsive-embed;
@include foundation-label;
@include foundation-media-object;
@include foundation-menu;
@include foundation-menu-icon;
@include foundation-off-canvas;
@include foundation-orbit;
@include foundation-pagination;
@include foundation-progress-bar;
@include foundation-slider;
@include foundation-sticky;
@include foundation-reveal;
@include foundation-switch;
@include foundation-table;
@include foundation-tabs;
@include foundation-thumbnail;
@include foundation-title-bar;
@include foundation-tooltip;
@include foundation-top-bar;

// If you'd like to include motion-ui the foundation-rails gem comes prepackaged with it, uncomment the 3 @imports, if you are not using the gem you need to install the motion-ui sass package.
//
// @include motion-ui-transitions;
// @include motion-ui-animations;
```
 Thanks

**Comment by sergibeltran** [comment]
Solved!

It seems `group :assets do` doesn't work on rails 5+ (I don't know on rails 4).

Works:
`gem 'foundation-rails'`

Fail:
```
group :assets do
  gem 'foundation-rails'
end
```

**Comment by Deckluhm** [comment]
This has been removed since Rails 4.

Source: http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0-gemfile
