### ISSUE TITLE
How to install from github?

### ISSUE THREAD

**Issue by xanview** [zurb/foundation-rails#224]
Hi there,

I'm trying to make my own branch for a bug fix in v5.3 - I have this in my gemfile just as a test:

```
gem 'foundation-rails', git: 'https://github.com/zurb/foundation-rails.git', tag: 'v5.5.3.2'
```

However, when I try to access the site, the browser says: "Uncaught ReferenceError: Foundation is not defined"

How would I install this gem direct from git rather than a package?

**Comment by Deckluhm** [comment]
- Fork the repository
- Create a new branch
- Fix your bug
- `gem 'foundation-rails', github: 'xanview/foundation-rails', branch: 'branch-name'`

For more information, check [Gemfile documentation](http://bundler.io/v1.14/man/gemfile.5.html) (there are sections for [Git repositories](http://bundler.io/v1.14/man/gemfile.5.html#GIT) and even [GitHub ones](http://bundler.io/v1.14/man/gemfile.5.html#GITHUB) and tons of other useful information about Gemfile in general).

**Comment by cooperka** [comment]
I'm getting the same JS error @ghost, I know it's several years later but were you ever able to resolve this?

**Comment by cooperka** [comment]
Solution: this was fixed in https://github.com/foundation/foundation-rails/pull/126 and must have been silently released without getting into github tag history.
