### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$primary-color"

### ISSUE THREAD

**Issue by yh0an** [zurb/foundation-rails#227]
Hello !

I got this error when I try to precompile assets : 
**Sass::SyntaxError: Undefined variable: "$primary-color"**
~/.rvm/gems/ruby-2.4.0/gems/foundation-rails-6.3.1.0/vendor/assets/scss/components/_accordion-menu.scss:11

I use sass-rails 5.0.6

I renamed application.css to application.scss and removed all /*require

My application.scss only contains @import "foundation/foundation_and_overrides";

Thanks for your help !

**Comment by Deckluhm** [comment]
Can you share your project?

**Comment by yh0an** [comment]
My problem came from a bad configuration of **config.assets.precompile**. I close this issue now. Thanks!

**Comment by vncgregorio** [comment]
@yh0an I'm facing the same problem here. How did you solve it?

**Comment by vncgregorio** [comment]
found what I was doing wrong! 

https://groups.google.com/forum/#!topic/activeadmin/FlqWTxpXBbs
