### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by BrandonRoehl** [zurb/foundation-rails#231]
![screen shot 2017-07-03 at 2 41 36 pm](https://user-images.githubusercontent.com/17932941/27806360-bfb005d8-5fff-11e7-92a3-bc19fca0b2ab.png)

`Uncaught ReferenceError: exports is not defined` occurs 34 different times when using
```ruby
gem 'foundation-rails' , '6.4.1.0'
```

The screenshot is from a completely new and blank app

```bash
rails new app-name
cd app-name
echo "gem 'foundation-rails' , '6.4.1.0'" > Gemfile
bundle install
rails g foundation:install
rails s
```
Then there are errors

**Comment by Yanchek99** [comment]
This appears to be an issue with how the rake task is moving the bower_components into the vendor assets folder.  Is there a reason we load each individually from `bower_components/foundation-sites/js rather then just use the foundation.js` from `bower_components/foundation-sites/dist/js/foundation.js`

**Comment by BrandonRoehl** [comment]
OK I'm making a fork and attempting to fix this then. Do you know how to add a pull request to the issue?

**Comment by BrandonRoehl** [comment]
I made a pull request at #232

**Comment by clay-f** [comment]
+1

**Comment by rgrabowski** [comment]
+1
