### ISSUE TITLE
Issue with the order of files in foundation_and_overrides.scss

### ISSUE THREAD

**Issue by Kulgar** [zurb/foundation-rails#243]
Hi, 

When we generate the files using rails g foundation:install, we get a strange import order in foundation_and_overrides.scss:

```
@include foundation-drilldown-menu;
@include foundation-dropdown;
@include foundation-dropdown-menu;
@include foundation-responsive-embed;
@include foundation-label;
@include foundation-media-object;
@include foundation-menu;
@include foundation-menu-icon;
```

As foundation-menu is included after foundation-dropdown, it overrides css rules (like display:none) when using a menu with dropdown because of the "menu" css class, breaking the dropdown functionality. 

It should rather be:

```
@include foundation-responsive-embed;
@include foundation-label;
@include foundation-media-object;
@include foundation-menu;
@include foundation-menu-icon;
@include foundation-drilldown-menu;
@include foundation-dropdown;
@include foundation-dropdown-menu;
```

Don't you think? 

Can you also check if there are some other misplaced includes?

**Comment by patricklindsay** [comment]
This is fixed in #237. Just wanting on a merge @mehlah @mhayes @kball ?
