### ISSUE TITLE
default install into new rails app not displaying nav properly.

### ISSUE THREAD

**Issue by bill-siftlocal** [zurb/foundation-rails#245]
https://stackoverflow.com/questions/46697128/foundation-6-top-bar-out-of-the-box-does-not-look-correct?noredirect=1#comment80411851_46697128

**Comment by slateb** [comment]
I am running into the same problem. It also appears that the `foundation_and_overrides.scss` file is not actually including all the `@include` mixins. When I try to add them to the bottom of the file I get an `Undefined mixin` error.

**Comment by slateb** [comment]
BTW I did run `rails g foundation:install` if having that info helps to figure out what's going on.

**Comment by ctalvarez** [comment]
I have the same problem

**Comment by RobinDaugherty** [comment]
Which mixins are missing? I'm running into this layout issue with dropdown menus in the topbar and everything mixin seems to be included, included "top-bar", "menu", and "drop-down-menu"...

**Comment by RobinDaugherty** [comment]
I was able to get everything working by backing down to foundation-rails 6.2. Both 6.3 and 6.4 are broken.

**Comment by adigitalnative** [comment]
Is this still the case, that the current version is broken, so use 6.2?

**Comment by patricklindsay** [comment]
We're using `foundation-rails (~> 6.4.1)` and having no such problems.

**Comment by derekmwright** [comment]
I used the following in my Gemfile to resolve the issue:
```
gem 'sass', '~> 3.1'
gem 'foundation-rails', '~> 6.4.3.0'
```

**Comment by ncoden** [comment]
Fixed with `foundation-rails` >= `v6.4.1`. Closing.
