### ISSUE TITLE
foundation-rails 6.4.1 prototype/_typescale.scss error

### ISSUE THREAD

**Issue by francesco-loreti** [zurb/foundation-rails#247]
Into foundation_and_overrides.scss I want use "@include foundation-prototype-classes;" but when I start the application I have this error:

`ActionView::Template::Error (You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend h1" on line 15 of C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/foundation-rails-6.4.1.2/vendor/assets/scss/prototype/_typescale.scss.`

So I can't use this extension. Any solution?

**Comment by FiloSpaTeam** [comment]
I've the same problem. :+1:

**Comment by FiloSpaTeam** [comment]
If you want you can use:
```
@include foundation-prototype-typescale;
@include foundation-prototype-text-utilities;
@include foundation-prototype-text-transformation;
@include foundation-prototype-text-decoration;
@include foundation-prototype-font-styling;
@include foundation-prototype-list-style-type;
@include foundation-prototype-rounded;
@include foundation-prototype-bordered;
@include foundation-prototype-shadow;
@include foundation-prototype-arrow;
@include foundation-prototype-separator;
@include foundation-prototype-overflow;
@include foundation-prototype-display;
@include foundation-prototype-position;
@include foundation-prototype-border-box;
@include foundation-prototype-border-none;
@include foundation-prototype-sizing;
```

I need at the moment only sizing prototype and the problem doesn't appear. So the problem is around typescale i think.

**Comment by ncoden** [comment]
Closing as we upgraded to Foundation v6.4.3. Please reopen if you still have the issue.
