### ISSUE TITLE
turbolinks and foundation-rails

### ISSUE THREAD

**Issue by daniel-costa** [zurb/foundation-rails#248]
I know we can find hundreds of issues related to that but so far, none solved my problem.

I've a rails app using `foundation-rails`, `turbolinks` and `jquery`. So far, I'm trying to get a sticky element to work and it's "half-working". When I load the page, it works, it's sticky but when I click on a link the new "page" doesn't get the sticky anymore.

After reading a load of issues, it looks we have to place the initialisation of foundation in a particular sequence of events, what I did in my `application.js` file:
```javascript
//= require jquery
//= require jquery_ujs
//= require foundation
//= require jquery.turbolinks
//= require turbolinks
//= require_tree .

$(document).on('turbolinks:load', function() {
  console.log("turbolinks:load")
  $(function(){ 
    console.log("JQuery")
    $(document).foundation();
  });
});
```

You can check the app here: https://reshel.herokuapp.com/

When I look at the console I get the 2 logs in it in both cases (first get and click on a link). If I put in the console `Foundation` I get a valid object too.

Any idea if this is a problem in the fondation-rails side?

**Comment by patricklindsay** [comment]
This is what I'm currently doing using turbolinks (5.0.1) & foundation-rails (6.4.1.3) with JS async set in production. 

```
# HAML HEAD
= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload', async: Rails.env.production?, defer: Rails.env.production?
```

```
# application.js
function ready() {
  if (window.initialized == true) {
   # Early exit when site has already initialized
    return;
  } else {
    window.initialized = true;
  }

  // Initialize foundation
  $(document).foundation();
}

document.addEventListener("turbolinks:load", ready);
$( document ).ready(ready);

```

**Comment by ncoden** [comment]
Closing as we upgraded to Foundation v6.4.3. Please reopen if you still have the issue.
