### ISSUE TITLE
Best practice query of foundation_and_overrides.scss

### ISSUE THREAD

**Issue by darbymanning** [zurb/foundation-rails#250]
Shouldn't `foundation_and_overrides.scss` be prefixed with an `_` as it is a partial that's imported in your own scss file? Perhaps it should really be `_foundation-and-overrides.scss` really?

**Comment by ncoden** [comment]
Partials are _parts of a project_ that may have dependencies in it. The main file of a package is not a partial as it does not rely on anything, even if the purpose of the package is to be included somewhere.
