### ISSUE TITLE
trouble starting project

### ISSUE THREAD

**Issue by Davey-Wright** [zurb/foundation-rails#268]
Not sure if I have configured things correctly, 

But my assets/stylesheets directory has not added the foundation library.
The foundation_and_overrides.scss file does not have any of the includes either.

https://github.com/Davey-Wright/foundation-test/tree/master/app/assets/stylesheets

Am i doing something wrong here? I have followed the steps exactly as instructed, but am having no luck with adding foundation to rails.

**Comment by dharanimanne** [comment]
Same issue with me. Trying out foundation the first time with Rails 5.2 and followed the README but it doesn't work. Also, there are no import statements of 'motion-ui' in the foundation_and_overrides.scss file.
