### ISSUE TITLE
Updating 6.5.1.0 require 'sprockets/es6' isn't working have to change to require 'sprockets/rails' 

### ISSUE THREAD

**Issue by brianmcoates** [zurb/foundation-rails#273]
When I updated to 6.5.1.0 and then start my rails sever I get 
```
/lib/ruby/gems/2.3.0/gems/foundation-rails-6.5.1.0/lib/foundation-rails.rb:2:in `require': cannot load such file -- sprockets/es6 (LoadError)
```

 to fix this I had to change the require to
```
 require 'sprockets/rails' 
```

**Comment by khiet** [comment]
I had this a few days ago, you can add `gem 'sprockets-es6'` to you Gemfile. I know it's not documented and annoying 😭 
This seems to be the commit that introduced this: https://github.com/zurb/foundation-rails/commit/a6c927db5f604d8d3e2e741389455b69d4c7aff2#diff-44263267796d33ed2765ce27a5ba5f3c

**Comment by brianmcoates** [comment]
@khiet Thank you! Yeah it seemed that they might have wanted to update to sprocket-rails but I'm not sure.
